# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGISGPTPlugin
                                 A QGIS plugin
 QGISGPTPlugin harnesses the power of ChatGPT to interpret natural language commands within QGIS. Simply describe your GIS tasks in natural language and let ChatGPT generate the Python code to execute them.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-31
        copyright            : (C) 2023 by Hennie Kotze
        email                : hennie@xaisim.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGISGPTPlugin class from file QGISGPTPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgisgpt_plugin import QGISGPTPlugin
    return QGISGPTPlugin(iface)
